var searchData=
[
  ['s_0',['Experimental Node(s)',['../experimental_node.html',1,'node_guide_landing_page']]],
  ['s_20signals_20as_20follows_3a_1',['of NAV data on L5 and S signals as follows:',['../classNAV_1_1IRNSSEphemeris.html#autotoc_md6',1,'']]],
  ['s_20sps_20signal_20are_20bad_2',['| 1 | Some or all navigation data on S SPS signal are bad',['../classNAV_1_1IRNSSEphemeris.html#autotoc_md9',1,'']]],
  ['sat_20system_20with_20higher_20priority_20found_20gps_20gal_20glo_3',['Case 1: New Sat System with higher priority found (GPS &amp;gt; GAL &amp;gt; GLO &amp;gt; ...)',['../SppKF.html#SppKF-InterChange-Case1',1,'']]],
  ['satellite_20change_4',['Pivot satellite change',['../RealTimeKinematics.html#RTK-PivotSatelliteChange',1,'']]],
  ['satellites_20used_5',['of satellites used',['../structNAV_1_1UlogFile_1_1VehicleGpsPosition.html#autotoc_md20',1,'']]],
  ['scale_20matrix_20g_6',['Gauss-Markov constant 𝛽 &amp;amp; Noise scale matrix G',['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Units-beta-G',1,'']]],
  ['scale_20matrix_20w_7',['scale matrix W',['../RealTimeKinematics.html#autotoc_md35',1,'Noise scale matrix W'],['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-Noise-Scale-matrix',1,'Noise scale matrix W'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Noise-Scale-matrix',1,'Noise scale matrix W']]],
  ['scenario_8',['Scenario',['../imu_simulator_node.html#imu_simulator_node_settings_scenario',1,'']]],
  ['scheme_20with_20nis_20test_9',['KF scheme with NIS test',['../RealTimeKinematics.html#autotoc_md49',1,'']]],
  ['selection_10',['Selection',['../left_panel.html#left_panel_selection',1,'']]],
  ['sensitivity_20matrix_11',['sensitivity matrix',['../SppBasics.html#SppBasics-measurementModel-sensitivityMatrix',1,'Design matrix / Measurement sensitivity matrix'],['../SppKF.html#SppKF-measurmentModel-sensitivityMatrix',1,'Measurement sensitivity matrix']]],
  ['sensitivity_20matrix_20h_12',['sensitivity Matrix H',['../RealTimeKinematics.html#autotoc_md41',1,'Measurement sensitivity Matrix H'],['../RealTimeKinematics.html#autotoc_md53',1,'Measurement sensitivity Matrix H'],['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-KF-H',1,'Measurement sensitivity Matrix H'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-KF-H',1,'Measurement sensitivity Matrix H'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Units-H',1,'Measurement sensitivity Matrix H']]],
  ['series_13',['series',['../LooselyCoupledKF_e.html#autotoc_md56',1,'Taylor series'],['../LooselyCoupledKF_n.html#autotoc_md58',1,'Taylor series']]],
  ['settings_14',['Settings',['../node_guide_introduction.html#node_guide_introduction_settings',1,'Node Settings'],['../rtklib_pos_converter_node.html#rtklib_pos_converter_node_settings',1,'Settings'],['../matrix_logger_node.html#matrix_logger_node_settings',1,'Settings'],['../rinex_obs_logger_node.html#rinex_obs_logger_node_settings',1,'Settings'],['../pos_vel_att_logger_node.html#pos_vel_att_logger_node_settings',1,'Settings'],['../csv_file_node.html#csv_file_node_settings',1,'Settings'],['../nmea_file_node.html#nmea_file_node_settings',1,'Settings'],['../rinex_nav_file_node.html#rinex_nav_file_node_settings',1,'Settings'],['../rinex_obs_file_node.html#rinex_obs_file_node_settings',1,'Settings'],['../rtklib_pos_file_node.html#rtklib_pos_file_node_settings',1,'Settings'],['../imu_simulator_node.html#imu_simulator_node_settings',1,'Settings'],['../demo_node.html#demo_node_settings',1,'Settings']]],
  ['settings_20and_20run_20flow_15',['EXAMPLE 2: Node Settings and run Flow',['../getting_started.html#getting_started_ex2',1,'']]],
  ['short_20form_16',['Short form',['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-ErrorStateEquations-ShortForm',1,'Short form'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-ErrorStateEquations-LocalLevelFrame-ShortForm',1,'Short form']]],
  ['shown_17',['of packages that are skipped until data rate is shown',['../classNAV_1_1experimental_1_1SkydelNetworkStream.html#autotoc_md22',1,'']]],
  ['sided_20test_18',['One sided Test',['../RealTimeKinematics.html#autotoc_md48',1,'']]],
  ['signal_19',['Signal',['../classNAV_1_1QZSSEphemeris.html#autotoc_md14',1,'Bit Location | Name | Target Signal'],['../classNAV_1_1QZSSEphemeris.html#autotoc_md17',1,'Bit Location | Name | Target Signal']]],
  ['signal_20are_20bad_20',['signal are bad',['../classNAV_1_1IRNSSEphemeris.html#autotoc_md8',1,'| 1 | Some or all navigation data on L5 SPS signal are bad'],['../classNAV_1_1IRNSSEphemeris.html#autotoc_md9',1,'| 1 | Some or all navigation data on S SPS signal are bad']]],
  ['signals_20as_20follows_3a_21',['of NAV data on L5 and S signals as follows:',['../classNAV_1_1IRNSSEphemeris.html#autotoc_md6',1,'']]],
  ['significant_20bit_20of_20iodc_20indicate_20fit_20intervals_3a_22',['2 MSBs (most significant bit) of IODC indicate fit intervals:',['../classNAV_1_1QZSSEphemeris.html#autotoc_md10',1,'']]],
  ['simulation_23',['Simulation',['../algorithms_landing_page.html#autotoc_md26',1,'']]],
  ['simulation_20models_24',['Simulation models',['../imu_simulator_node.html#imu_simulator_node_settings_simulation_models',1,'']]],
  ['simulation_20stop_20condition_25',['Simulation Stop Condition',['../imu_simulator_node.html#imu_simulator_node_settings_simulation_stop_condition',1,'']]],
  ['simulator_26',['IMU Simulator',['../ImuSimulator.html',1,'algorithms_landing_page']]],
  ['simulator_20node_27',['Imu Simulator Node',['../imu_simulator_node.html',1,'node_guide_landing_page']]],
  ['since_20two_20time_20points_20are_20required_20to_20calculate_20a_20data_20rate_28',['of packages for averaging dataRate (minimum is &apos;2&apos;, since two time points are required to calculate a data rate)',['../classNAV_1_1experimental_1_1SkydelNetworkStream.html#autotoc_md21',1,'']]],
  ['single_20difference_29',['Single Difference',['../RealTimeKinematics.html#RTK-SingleDifference',1,'']]],
  ['single_20difference_30',['Single difference',['../RealTimeKinematics.html#autotoc_md30',1,'']]],
  ['single_20gnss_20observation_20equation_31',['Single GNSS Observation Equation',['../RealTimeKinematics.html#RTK-SingleObservationEquations',1,'']]],
  ['single_20point_20positioning_20basics_32',['Single Point Positioning Basics',['../SppBasics.html',1,'algorithms_landing_page']]],
  ['single_20point_20positioning_20using_20kalman_20filtering_33',['Single Point Positioning using Kalman Filtering',['../SppKF.html',1,'algorithms_landing_page']]],
  ['single_20point_20positioning_20using_20weighed_20least_20squares_20estimation_34',['Single Point Positioning using (Weighed) Least Squares Estimation',['../SppLSE.html',1,'algorithms_landing_page']]],
  ['skipped_20until_20data_20rate_20is_20shown_35',['of packages that are skipped until data rate is shown',['../classNAV_1_1experimental_1_1SkydelNetworkStream.html#autotoc_md22',1,'']]],
  ['some_20or_20all_20navigation_20data_20on_20l5_20sps_20signal_20are_20bad_36',['| 1 | Some or all navigation data on L5 SPS signal are bad',['../classNAV_1_1IRNSSEphemeris.html#autotoc_md8',1,'']]],
  ['some_20or_20all_20navigation_20data_20on_20s_20sps_20signal_20are_20bad_37',['| 1 | Some or all navigation data on S SPS signal are bad',['../classNAV_1_1IRNSSEphemeris.html#autotoc_md9',1,'']]],
  ['spp_20node_38',['SPP Node',['../single_point_positioning_node.html',1,'node_guide_landing_page']]],
  ['sppsolutionlogger_20node_39',['SppSolutionLogger Node',['../spp_solution_logger_node.html',1,'node_guide_landing_page']]],
  ['sps_20signal_20are_20bad_40',['SPS signal are bad',['../classNAV_1_1IRNSSEphemeris.html#autotoc_md8',1,'| 1 | Some or all navigation data on L5 SPS signal are bad'],['../classNAV_1_1IRNSSEphemeris.html#autotoc_md9',1,'| 1 | Some or all navigation data on S SPS signal are bad']]],
  ['square_20root_20implementation_20of_20the_20kalman_20filter_41',['Square root implementation of the Kalman filter',['../KalmanFilterBasics.html#KalmanFilterBasics-SQR',1,'']]],
  ['squared_20nis_42',['Normalized Innovation Squared (NIS)',['../RealTimeKinematics.html#autotoc_md47',1,'']]],
  ['squares_20estimation_43',['Squares Estimation',['../SppLSE.html#SppLSE-LseAlgorithm',1,'Algorithm - Linearized (Weighed) Least Squares Estimation'],['../SppLSE.html',1,'Single Point Positioning using (Weighed) Least Squares Estimation']]],
  ['start_20time_44',['Start Time',['../imu_simulator_node.html#imu_simulator_node_settings_start_time',1,'']]],
  ['started_45',['Started',['../Dev_Getting_Started.html',1,'Getting Started'],['../getting_started.html',1,'Getting Started']]],
  ['started_20as_20a_20user_46',['Getting Started as a User',['../main_introduction.html#introduction_users',1,'']]],
  ['state_47',['State',['../RealTimeKinematics.html#RTK-State',1,'']]],
  ['state_48',['Correcting float state',['../RealTimeKinematics.html#RTK-CorrectingFloatState',1,'']]],
  ['state_20equations_49',['State Equations',['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-ErrorStateEquations',1,'Earth Frame Error State Equations'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-ErrorStateEquations-LocalLevelFrame',1,'Local-Level Frame Error State Equations']]],
  ['state_20transition_20matrix_50',['State transition matrix',['../SppKF.html#SppKF-processModel-stateTransitionMatrix',1,'']]],
  ['state_20transition_20matrix_20𝚽_51',['State transition matrix 𝚽',['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-KF-Phi',1,'State transition matrix 𝚽'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-KF-Phi',1,'State transition matrix 𝚽']]],
  ['state_20transition_20matrix_20𝚽_20process_20noise_20covariance_20matrix_20q_52',['State transition matrix 𝚽 Process noise covariance matrix Q',['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-KF-Phi-Q',1,'State transition matrix 𝚽 &amp; Process noise covariance matrix Q'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-KF-Phi-Q',1,'State transition matrix 𝚽 &amp; Process noise covariance matrix Q']]],
  ['state_20transition_20matrix_20𝛟_53',['State transition matrix 𝛟',['../RealTimeKinematics.html#autotoc_md32',1,'']]],
  ['state_20with_20noise_54',['State with Noise',['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-Noise',1,'Augmented State with Noise'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Noise',1,'Augmented State with Noise']]],
  ['states_55',['Node States',['../Core_Node.html#Core_Node_State',1,'']]],
  ['step_20correction_56',['Two step correction',['../RealTimeKinematics.html#RTK-syncTwoStep',1,'']]],
  ['stop_20condition_57',['Simulation Stop Condition',['../imu_simulator_node.html#imu_simulator_node_settings_simulation_stop_condition',1,'']]],
  ['structure_58',['Repository structure',['../Dev_Getting_Started.html#Dev_Getting_Started_Structure',1,'']]],
  ['style_59',['Style',['../bar_edit_implot_style.html',1,'ImPlot Style'],['../bar_edit_node_editor_style.html',1,'Node Editor Style']]],
  ['synchronization_20correction_60',['Synchronization correction',['../RealTimeKinematics.html#RTK-SyncCorrection',1,'']]],
  ['synchronizing_20base_20and_20rover_20observations_61',['2. Synchronizing base and rover observations',['../RealTimeKinematics.html#autotoc_md28',1,'']]],
  ['system_20change_62',['Inter system time difference reference system change',['../SppKF.html#SppKF-InterChange',1,'']]],
  ['system_20matrix_20f_63',['System matrix F',['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Units-F',1,'']]],
  ['system_20model_64',['System Model',['../SppKF.html#SppKF-processModel-systemModel',1,'System Model'],['../RealTimeKinematics.html#RTK-SystemModel',1,'System Model']]],
  ['system_20time_20difference_20reference_20system_20change_65',['Inter system time difference reference system change',['../SppKF.html#SppKF-InterChange',1,'']]],
  ['system_20with_20higher_20priority_20found_20gps_20gal_20glo_66',['Case 1: New Sat System with higher priority found (GPS &amp;gt; GAL &amp;gt; GLO &amp;gt; ...)',['../SppKF.html#SppKF-InterChange-Case1',1,'']]],
  ['system_20within_20an_20epoch_67',['Case 2: No observation for reference system within an epoch',['../SppKF.html#SppKF-InterChange-Case2',1,'']]]
];
