var searchData=
[
  ['p_0',['P',['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-KF-P',1,'Error covariance matrix P'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-KF-P',1,'Error covariance matrix P'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Units-P',1,'Error covariance matrix P']]],
  ['packages_20for_20averaging_20datarate_20minimum_20is_202_20since_20two_20time_20points_20are_20required_20to_20calculate_20a_20data_20rate_1',['of packages for averaging dataRate (minimum is &apos;2&apos;, since two time points are required to calculate a data rate)',['../classNAV_1_1experimental_1_1SkydelNetworkStream.html#autotoc_md21',1,'']]],
  ['packages_20that_20are_20skipped_20until_20data_20rate_20is_20shown_2',['of packages that are skipped until data rate is shown',['../classNAV_1_1experimental_1_1SkydelNetworkStream.html#autotoc_md22',1,'']]],
  ['panel_3',['Left Panel',['../left_panel.html',1,'gui_landing_page']]],
  ['parameters_20with_20update_20rate_20lesser_20than_2030_20minutes_4',['160 to 255 | &amp;lt; 30 min | For the ephemeris and clock parameters with update rate lesser than 30 minutes',['../classNAV_1_1IRNSSEphemeris.html#autotoc_md5',1,'']]],
  ['pins_5',['Pins',['../node_connections.html#node_connections_pins',1,'']]],
  ['pins_20and_20connections_6',['Pins and Connections',['../node_connections.html',1,'user_manual_landing_page']]],
  ['pitch_20angle_7',['Pitch angle',['../ImuSimulator.html#ImuSimulator-Flight-Angles-Pitch',1,'']]],
  ['pivot_20satellite_20change_8',['Pivot satellite change',['../RealTimeKinematics.html#RTK-PivotSatelliteChange',1,'']]],
  ['plot_20node_9',['Plot Node',['../plot_node.html',1,'node_guide_landing_page']]],
  ['point_20positioning_20basics_10',['Single Point Positioning Basics',['../SppBasics.html',1,'algorithms_landing_page']]],
  ['point_20positioning_20using_20kalman_20filtering_11',['Single Point Positioning using Kalman Filtering',['../SppKF.html',1,'algorithms_landing_page']]],
  ['point_20positioning_20using_20weighed_20least_20squares_20estimation_12',['Single Point Positioning using (Weighed) Least Squares Estimation',['../SppLSE.html',1,'algorithms_landing_page']]],
  ['points_20are_20required_20to_20calculate_20a_20data_20rate_13',['of packages for averaging dataRate (minimum is &apos;2&apos;, since two time points are required to calculate a data rate)',['../classNAV_1_1experimental_1_1SkydelNetworkStream.html#autotoc_md21',1,'']]],
  ['position_14',['Position',['../ImuIntegrator_e.html#ImuIntegrator-Mechanization-e-Position',1,'Position'],['../ImuIntegrator_n.html#ImuIntegrator-Mechanization-n-Position',1,'Position']]],
  ['position_20equations_15',['Position Equations',['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-ErrorStateEquations-Derivation-Position',1,'Position Equations'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-ErrorStateEquations-LocalLevelFrame-Derivation-Position',1,'Position Equations']]],
  ['position_20rotation_16',['IMU Position &amp;amp; Rotation',['../imu_simulator_node.html#imu_simulator_node_settings_imu_position_rotation',1,'']]],
  ['position_20velocity_20attitude_17',['Position Velocity Attitude',['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-Corrections-State',1,'Position, Velocity, Attitude'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Corrections-State',1,'Position, Velocity, Attitude']]],
  ['positioning_18',['Real-Time Kinematics Positioning',['../RealTimeKinematics.html',1,'algorithms_landing_page']]],
  ['positioning_20basics_19',['Single Point Positioning Basics',['../SppBasics.html',1,'algorithms_landing_page']]],
  ['positioning_20using_20kalman_20filtering_20',['Single Point Positioning using Kalman Filtering',['../SppKF.html',1,'algorithms_landing_page']]],
  ['positioning_20using_20weighed_20least_20squares_20estimation_21',['Single Point Positioning using (Weighed) Least Squares Estimation',['../SppLSE.html',1,'algorithms_landing_page']]],
  ['posvelattfile_20node_22',['PosVelAttFile Node',['../pos_vel_att_file_node.html',1,'node_guide_landing_page']]],
  ['posvelattinitializer_20node_23',['PosVelAttInitializer Node',['../pos_vel_att_initializer_node.html',1,'node_guide_landing_page']]],
  ['posvelattlogger_20node_24',['PosVelAttLogger Node',['../pos_vel_att_logger_node.html',1,'node_guide_landing_page']]],
  ['prediction_25',['Using Bayes&apos; Theorem for Prediction',['../KalmanFilterBasics.html#KalmanFilterBasics-Prediction',1,'']]],
  ['preface_26',['Preface',['../node_guide_introduction.html#node_guide_introduction_preface',1,'']]],
  ['priority_20found_20gps_20gal_20glo_27',['Case 1: New Sat System with higher priority found (GPS &amp;gt; GAL &amp;gt; GLO &amp;gt; ...)',['../SppKF.html#SppKF-InterChange-Case1',1,'']]],
  ['process_20model_28',['Process Model',['../SppKF.html#SppKF-processModel',1,'']]],
  ['process_20noise_20covariance_20matrix_29',['Process noise covariance matrix',['../SppKF.html#SppKF-processModel-processNoise',1,'']]],
  ['process_20noise_20covariance_20matrix_20q_30',['Process noise covariance matrix Q',['../RealTimeKinematics.html#autotoc_md33',1,'Process noise covariance matrix Q'],['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-KF-Q',1,'Process noise covariance matrix Q'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-KF-Q',1,'Process noise covariance matrix Q'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Units-Q',1,'Process noise covariance matrix Q'],['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-KF-Phi-Q',1,'State transition matrix 𝚽 &amp; Process noise covariance matrix Q'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-KF-Phi-Q',1,'State transition matrix 𝚽 &amp; Process noise covariance matrix Q']]],
  ['process_20noise_20definition_31',['process noise definition',['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-Groves-process-noise-definition',1,'Groves' process noise definition'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Groves-process-noise-definition',1,'Groves' process noise definition']]],
  ['programming_32',['Flow-Based Programming',['../main_introduction.html#introduction_programming',1,'']]],
  ['programming_33',['What is flow-based programming',['../main_introduction.html#introduction_fbp',1,'']]],
  ['programming_20and_20instinct_34',['Flow-based Programming and INSTINCT',['../main_introduction.html#introduction_fbp_instinct',1,'']]],
  ['project_20introduction_35',['Project Introduction',['../main_introduction.html',1,'']]],
  ['project_20tasks_20json_36',['How to work with the project (tasks.json)',['../Dev_Getting_Started.html#Dev_Getting_Started_VSCode_tasks',1,'']]],
  ['propagation_37',['propagation',['../RealTimeKinematics.html#RTK-ErrorPropagation',1,'Error propagation'],['../SppKF.html#SppKF-InterChange-ErrorProp',1,'Error propagation']]],
  ['propagation_20comparison_38',['Quaternion propagation comparison',['../ImuIntegrator_n.html#ImuIntegrator-Mechanization-n-Attitude-Quaternion-Comparison',1,'']]],
  ['propagation_20of_20direction_20cosine_20matrix_20with_20time_39',['Propagation of direction cosine matrix with time',['../ImuIntegrator_e.html#ImuIntegrator-Mechanization-e-Attitude-DCM',1,'Propagation of direction cosine matrix with time'],['../ImuIntegrator_n.html#ImuIntegrator-Mechanization-n-Attitude-DCM',1,'Propagation of direction cosine matrix with time']]],
  ['propagation_20of_20euler_20angles_20with_20time_40',['Propagation of Euler angles with time',['../ImuIntegrator_n.html#ImuIntegrator-Mechanization-n-Attitude-Euler',1,'']]],
  ['propagation_20of_20quaternion_20with_20time_41',['Propagation of quaternion with time',['../ImuIntegrator_e.html#ImuIntegrator-Mechanization-e-Attitude-Quaternion',1,'Propagation of quaternion with time'],['../ImuIntegrator_n.html#ImuIntegrator-Mechanization-n-Attitude-Quaternion',1,'Propagation of quaternion with time']]],
  ['pseudorange_20difference_42',['Carrier-Pseudorange Difference',['../RealTimeKinematics.html#RTK-CarrierPseudorangeDifference',1,'']]],
  ['publications_43',['Publications',['../main_introduction.html#introduction_publications',1,'']]]
];
