var searchData=
[
  ['r_0',['R',['../RealTimeKinematics.html#autotoc_md42',1,'Measurement noise covariance matrix R'],['../RealTimeKinematics.html#autotoc_md54',1,'Measurement noise covariance matrix R'],['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-KF-R',1,'Measurement noise covariance matrix R'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-KF-R',1,'Measurement noise covariance matrix R'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Units-R',1,'Measurement noise covariance matrix R']]],
  ['random_20walk_1',['Random Walk',['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-Noise-RW',1,'Random Walk'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Noise-RW',1,'Random Walk']]],
  ['range_20update_20description_2',['IODEC range | Update | Description',['../classNAV_1_1IRNSSEphemeris.html#autotoc_md4',1,'']]],
  ['rate_3',['of packages for averaging dataRate (minimum is &apos;2&apos;, since two time points are required to calculate a data rate)',['../classNAV_1_1experimental_1_1SkydelNetworkStream.html#autotoc_md21',1,'']]],
  ['rate_20is_20shown_4',['of packages that are skipped until data rate is shown',['../classNAV_1_1experimental_1_1SkydelNetworkStream.html#autotoc_md22',1,'']]],
  ['rate_20lesser_20than_2030_20minutes_5',['160 to 255 | &amp;lt; 30 min | For the ephemeris and clock parameters with update rate lesser than 30 minutes',['../classNAV_1_1IRNSSEphemeris.html#autotoc_md5',1,'']]],
  ['rate_20measurements_6',['Angular Rate Measurements',['../ImuSimulator.html#ImuSimulator-AngularRate-Measurements',1,'']]],
  ['real_20time_20kinematics_20positioning_7',['Real-Time Kinematics Positioning',['../RealTimeKinematics.html',1,'algorithms_landing_page']]],
  ['receiver_20internal_20clock_20error_8',['1. Correction of receiver internal clock error',['../RealTimeKinematics.html#autotoc_md27',1,'']]],
  ['reference_20system_20change_9',['Inter system time difference reference system change',['../SppKF.html#SppKF-InterChange',1,'']]],
  ['reference_20system_20within_20an_20epoch_10',['Case 2: No observation for reference system within an epoch',['../SppKF.html#SppKF-InterChange-Case2',1,'']]],
  ['relations_11',['Basic relations',['../KalmanFilterBasics.html#KalmanFilterBasics-Basic',1,'']]],
  ['repository_20structure_12',['Repository structure',['../Dev_Getting_Started.html#Dev_Getting_Started_Structure',1,'']]],
  ['required_20to_20calculate_20a_20data_20rate_13',['of packages for averaging dataRate (minimum is &apos;2&apos;, since two time points are required to calculate a data rate)',['../classNAV_1_1experimental_1_1SkydelNetworkStream.html#autotoc_md21',1,'']]],
  ['residuals_14',['Measurement residuals',['../SppLSE.html#SppLSE-measurmentModel-residuals',1,'']]],
  ['resolution_15',['Ambiguity resolution',['../RealTimeKinematics.html#RTK-AmbiguityResolution',1,'']]],
  ['rinexnavfile_20node_16',['RinexNavFile Node',['../rinex_nav_file_node.html',1,'node_guide_landing_page']]],
  ['rinexobsfile_20node_17',['RinexObsFile Node',['../rinex_obs_file_node.html',1,'node_guide_landing_page']]],
  ['rinexobslogger_20node_18',['RinexObsLogger Node',['../rinex_obs_logger_node.html',1,'node_guide_landing_page']]],
  ['roll_20angle_19',['Roll angle',['../ImuSimulator.html#ImuSimulator-Flight-Angles-Roll',1,'']]],
  ['root_20implementation_20of_20the_20kalman_20filter_20',['Square root implementation of the Kalman filter',['../KalmanFilterBasics.html#KalmanFilterBasics-SQR',1,'']]],
  ['rotation_21',['IMU Position &amp;amp; Rotation',['../imu_simulator_node.html#imu_simulator_node_settings_imu_position_rotation',1,'']]],
  ['rover_20observations_22',['2. Synchronizing base and rover observations',['../RealTimeKinematics.html#autotoc_md28',1,'']]],
  ['rtklibposconverter_20node_23',['RtklibPosConverter Node',['../rtklib_pos_converter_node.html',1,'node_guide_landing_page']]],
  ['rtklibposfile_20node_24',['RtklibPosFile Node',['../rtklib_pos_file_node.html',1,'node_guide_landing_page']]],
  ['run_25',['Run',['../main_menu_bar.html#bar_run',1,'']]],
  ['run_20flow_26',['EXAMPLE 2: Node Settings and run Flow',['../getting_started.html#getting_started_ex2',1,'']]],
  ['runge_20kutta_204th_20order_27',['Runge Kutta 4th order',['../ImuIntegrator_e.html#ImuIntegrator-e-Numerical-Integration-RK4',1,'']]]
];
