var searchData=
[
  ['calculate_20a_20data_20rate_0',['of packages for averaging dataRate (minimum is &apos;2&apos;, since two time points are required to calculate a data rate)',['../classNAV_1_1experimental_1_1SkydelNetworkStream.html#autotoc_md21',1,'']]],
  ['calculation_1',['Trajectory calculation',['../ImuSimulator.html#ImuSimulator-Trajectory',1,'']]],
  ['can_20be_20found_20according_20to_20the_20following_20table_3a_2',['The IODEC values can be found according to the following table:',['../classNAV_1_1IRNSSEphemeris.html#autotoc_md3',1,'']]],
  ['carrier_20geometry_20difference_3',['Carrier-Geometry Difference',['../RealTimeKinematics.html#RTK-CarrierGeometryDifference',1,'']]],
  ['carrier_20pseudorange_20difference_4',['Carrier-Pseudorange Difference',['../RealTimeKinematics.html#RTK-CarrierPseudorangeDifference',1,'']]],
  ['case_201_3a_20low_20elevation_5',['Case 1: Low elevation',['../RealTimeKinematics.html#RTK-PivotCase1',1,'']]],
  ['case_201_3a_20new_20sat_20system_20with_20higher_20priority_20found_20gps_20gal_20glo_6',['Case 1: New Sat System with higher priority found (GPS &amp;gt; GAL &amp;gt; GLO &amp;gt; ...)',['../SppKF.html#SppKF-InterChange-Case1',1,'']]],
  ['case_202_3a_20no_20observation_20for_20reference_20system_20within_20an_20epoch_7',['Case 2: No observation for reference system within an epoch',['../SppKF.html#SppKF-InterChange-Case2',1,'']]],
  ['case_202_3a_20not_20observed_8',['Case 2: Not observed',['../RealTimeKinematics.html#RTK-PivotCase2',1,'']]],
  ['change_9',['change',['../SppKF.html#SppKF-InterChange',1,'Inter system time difference reference system change'],['../RealTimeKinematics.html#RTK-PivotSatelliteChange',1,'Pivot satellite change']]],
  ['circular_10',['Circular',['../ImuSimulator.html#ImuSimulator-Trajectory-Circular',1,'']]],
  ['citation_11',['License and Citation',['../main_introduction.html#introduction_cite',1,'']]],
  ['clock_20error_12',['1. Correction of receiver internal clock error',['../RealTimeKinematics.html#autotoc_md27',1,'']]],
  ['clock_20parameters_20with_20update_20rate_20lesser_20than_2030_20minutes_13',['160 to 255 | &amp;lt; 30 min | For the ephemeris and clock parameters with update rate lesser than 30 minutes',['../classNAV_1_1IRNSSEphemeris.html#autotoc_md5',1,'']]],
  ['colormap_20editor_14',['Colormap Editor',['../bar_edit_colormap_editor.html',1,'advanced_gui_landing_page']]],
  ['combiner_20node_15',['Combiner Node',['../combiner_node.html',1,'node_guide_landing_page']]],
  ['command_20line_20arguments_16',['Command line arguments',['../Dev_Getting_Started.html#Dev_Getting_Started_Cmd',1,'']]],
  ['comparison_17',['comparison',['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Appendix-ErrorStateEquations-LocalLevelFrame-Comparison',1,'Error Equations comparison'],['../ImuIntegrator_n.html#ImuIntegrator-Mechanization-n-Attitude-Quaternion-Comparison',1,'Quaternion propagation comparison']]],
  ['computation_18',['Computation',['../RealTimeKinematics.html#autotoc_md37',1,'']]],
  ['condition_19',['Simulation Stop Condition',['../imu_simulator_node.html#imu_simulator_node_settings_simulation_stop_condition',1,'']]],
  ['connect_20nodes_20',['Connect Nodes',['../node_guide_introduction.html#node_guide_introduction_connect',1,'']]],
  ['connections_21',['Connections',['../node_connections.html#node_connections_connections',1,'Connections'],['../rtklib_pos_converter_node.html#rtklib_pos_converter_node_connections',1,'Connections'],['../rinex_obs_logger_node.html#rinex_obs_logger_node_connections',1,'Connections'],['../pos_vel_att_logger_node.html#pos_vel_att_logger_node_connections',1,'Connections'],['../matrix_logger_node.html#matrix_logger_node_connections',1,'Connections'],['../csv_file_node.html#csv_file_node_connections',1,'Connections'],['../nmea_file_node.html#nmea_file_node_connections',1,'Connections'],['../rinex_nav_file_node.html#rinex_nav_file_node_connections',1,'Connections'],['../rinex_obs_file_node.html#rinex_obs_file_node_connections',1,'Connections'],['../rtklib_pos_file_node.html#rtklib_pos_node_connections',1,'Connections'],['../imu_simulator_node.html#imu_simulator_node_connections',1,'Connections'],['../demo_node.html#demo_node_connections',1,'Connections'],['../node_connections.html',1,'Pins and Connections']]],
  ['constant_20𝛽_20noise_20scale_20matrix_20g_22',['Gauss-Markov constant 𝛽 &amp;amp; Noise scale matrix G',['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Units-beta-G',1,'']]],
  ['contact_23',['Contact',['../main_introduction.html#introduction_contact',1,'']]],
  ['content_24',['Zoom to Content',['../left_panel.html#left_panel_zoom_to_content',1,'']]],
  ['context_20menu_25',['Context Menu',['../node_guide_introduction.html#node_guide_introduction_context',1,'']]],
  ['correcting_20float_20state_26',['Correcting float state',['../RealTimeKinematics.html#RTK-CorrectingFloatState',1,'']]],
  ['correction_27',['Using Bayes&apos; Theorem for Update/Correction',['../KalmanFilterBasics.html#KalmanFilterBasics-Update',1,'']]],
  ['correction_28',['correction',['../RealTimeKinematics.html#RTK-SyncCorrection',1,'Synchronization correction'],['../RealTimeKinematics.html#RTK-syncTwoStep',1,'Two step correction']]],
  ['correction_20of_20receiver_20internal_20clock_20error_29',['1. Correction of receiver internal clock error',['../RealTimeKinematics.html#autotoc_md27',1,'']]],
  ['corrections_30',['Corrections',['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-Corrections',1,'Corrections'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Corrections',1,'Corrections']]],
  ['correlated_20measurement_20error_31',['Correlated measurement error',['../RealTimeKinematics.html#autotoc_md43',1,'']]],
  ['cosine_20matrix_20with_20time_32',['cosine matrix with time',['../ImuIntegrator_e.html#ImuIntegrator-Mechanization-e-Attitude-DCM',1,'Propagation of direction cosine matrix with time'],['../ImuIntegrator_n.html#ImuIntegrator-Mechanization-n-Attitude-DCM',1,'Propagation of direction cosine matrix with time']]],
  ['coupled_20kalman_20filter_20earth_20fixed_20frame_33',['INS/GNSS Loosely-coupled Kalman Filter (Earth-fixed frame)',['../LooselyCoupledKF_e.html',1,'algorithms_landing_page']]],
  ['coupled_20kalman_20filter_20local_20navigation_20frame_34',['INS/GNSS Loosely-coupled Kalman Filter (local-navigation frame)',['../LooselyCoupledKF_n.html',1,'algorithms_landing_page']]],
  ['covariance_35',['Updating Ambiguity covariance',['../RealTimeKinematics.html#RTK-UpdatingAmbiguityCovariance',1,'']]],
  ['covariance_20matrix_36',['covariance matrix',['../SppKF.html#SppKF-measurmentModel-measurementNoise',1,'Measurement noise covariance matrix'],['../SppKF.html#SppKF-processModel-processNoise',1,'Process noise covariance matrix']]],
  ['covariance_20matrix_20p_37',['covariance matrix P',['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-KF-P',1,'Error covariance matrix P'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-KF-P',1,'Error covariance matrix P'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Units-P',1,'Error covariance matrix P']]],
  ['covariance_20matrix_20q_38',['covariance matrix Q',['../RealTimeKinematics.html#autotoc_md33',1,'Process noise covariance matrix Q'],['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-KF-Q',1,'Process noise covariance matrix Q'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-KF-Q',1,'Process noise covariance matrix Q'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Units-Q',1,'Process noise covariance matrix Q'],['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-KF-Phi-Q',1,'State transition matrix 𝚽 &amp; Process noise covariance matrix Q'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-KF-Phi-Q',1,'State transition matrix 𝚽 &amp; Process noise covariance matrix Q']]],
  ['covariance_20matrix_20r_39',['covariance matrix R',['../RealTimeKinematics.html#autotoc_md42',1,'Measurement noise covariance matrix R'],['../RealTimeKinematics.html#autotoc_md54',1,'Measurement noise covariance matrix R'],['../LooselyCoupledKF_e.html#LooselyCoupledKF_e-KF-R',1,'Measurement noise covariance matrix R'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-KF-R',1,'Measurement noise covariance matrix R'],['../LooselyCoupledKF_n.html#LooselyCoupledKF_n-Units-R',1,'Measurement noise covariance matrix R']]],
  ['creating_20own_20data_20types_40',['Creating own data types',['../Dev_Getting_Started.html#Dev_Getting_Started_Create_Node_Data',1,'']]],
  ['creating_20your_20first_20node_41',['Creating your first node',['../Dev_Getting_Started.html#Dev_Getting_Started_Create_Node',1,'']]],
  ['csvfile_20node_42',['CsvFile Node',['../csv_file_node.html',1,'node_guide_landing_page']]]
];
