/// This file is part of INSTINCT, the INS Toolkit for Integrated
/// Navigation Concepts and Training by the Institute of Navigation of
/// the University of Stuttgart, Germany.
///
/// This Source Code Form is subject to the terms of the Mozilla Public
/// License, v. 2.0. If a copy of the MPL was not distributed with this
/// file, You can obtain one at https://mozilla.org/MPL/2.0/.
///
/// <-- KEEP ONE EMPTY LINE HERE AND MAKE LICENSE COMMENTS only 2 slashes '//'
///
/// @file INS_1581_19O.hpp
/// @brief Test data for the INS_1581.19O
/// @author M. Maier (marcel.maier@ins.uni-stuttgart.de)
/// @date 2023-01-13

#pragma once

#include "NodeData/GNSS/GnssObs.hpp"

using Pseudorange = NAV::GnssObs::ObservationData::Pseudorange;
using CarrierPhase = NAV::GnssObs::ObservationData::CarrierPhase;

namespace NAV::TESTS::RinexObsFileTests::v3_04
{
/// @brief Test data for the INS_1581.19O
const std::vector<GnssObs> gnssObs_INS_1581_19O = {
    { /* .insTime = */ InsTime{ 2019, 06, 07, 00, 00, 0.0000000, GPST },
      /* .data = */ std::vector<GnssObs::ObservationData>{
          GnssObs::ObservationData{ /* .satSigId =     */ { B02, 5 },
                                    /* .code =         */ Code::B2I,
                                    /* .pseudorange =  */ Pseudorange{ .value = 40042574.312, .SSI = 6 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 208512218.973, .SSI = 6, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,   // observations contain no doppler
                                    /* .CN0 =          */ std::nullopt }, // observations contain no doppler
          GnssObs::ObservationData{ /* .satSigId =     */ { B07, 5 },
                                    /* .code =         */ Code::B7I,
                                    /* .pseudorange =  */ Pseudorange{ .value = 40042567.271, .SSI = 6 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 161234863.439, .SSI = 6, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { B06, 5 },
                                    /* .code =         */ Code::B6I,
                                    /* .pseudorange =  */ Pseudorange{ .value = 40042570.299, .SSI = 6 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 169433249.441, .SSI = 6, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { B02, 20 },
                                    /* .code =         */ Code::B2I,
                                    /* .pseudorange =  */ Pseudorange{ .value = 23482518.059, .SSI = 7 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 122279657.002, .SSI = 7, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { B06, 20 },
                                    /* .code =         */ Code::B6I,
                                    /* .pseudorange =  */ Pseudorange{ .value = 23482511.079, .SSI = 8 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 99362215.276, .SSI = 8, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { B02, 23 },
                                    /* .code =         */ Code::B2I,
                                    /* .pseudorange =  */ Pseudorange{ .value = 22903200.752, .SSI = 8 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 119262990.966, .SSI = 8, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { E01, 2 },
                                    /* .code =         */ Code::E1C,
                                    /* .pseudorange =  */ Pseudorange{ .value = 25642437.304, .SSI = 7 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 134751934.729, .SSI = 7, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { E06, 2 },
                                    /* .code =         */ Code::E6C,
                                    /* .pseudorange =  */ Pseudorange{ .value = 25642432.151, .SSI = 8 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 109376551.964, .SSI = 8, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { E05, 2 },
                                    /* .code =         */ Code::E5Q,
                                    /* .pseudorange =  */ Pseudorange{ .value = 25642432.913, .SSI = 7 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 100626434.851, .SSI = 7, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { E07, 2 },
                                    /* .code =         */ Code::E7Q,
                                    /* .pseudorange =  */ Pseudorange{ .value = 25642430.497, .SSI = 7 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 103251463.969, .SSI = 7, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { E08, 2 },
                                    /* .code =         */ Code::E8Q,
                                    /* .pseudorange =  */ Pseudorange{ .value = 25642431.399, .SSI = 7 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 101938948.985, .SSI = 7, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { E01, 13 },
                                    /* .code =         */ Code::E1C,
                                    /* .pseudorange =  */ Pseudorange{ .value = 28469196.889, .SSI = 3 },
                                    /* .carrierPhase = */ std::nullopt, // no carrierPhase, but pseudorange exists. This happens if the CN0 is so small that the PLL could not lock, even if the DLL has locked (= pseudorange available). The observation is still valid.
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { E01, 20 },
                                    /* .code =         */ Code::E1C,
                                    /* .pseudorange =  */ Pseudorange{ .value = 22672683.828, .SSI = 6 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 119145771.042, .SSI = 6, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { G01, 2 },
                                    /* .code =         */ Code::G1C,
                                    /* .pseudorange =  */ Pseudorange{ .value = 22458066.119, .SSI = 7 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 118017952.089, .SSI = 7, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { G01, 2 },
                                    /* .code =         */ Code::G1W,
                                    /* .pseudorange =  */ Pseudorange{ .value = 22458065.104, .SSI = 5 },
                                    /* .carrierPhase = */ std::nullopt,
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { G02, 2 },
                                    /* .code =         */ Code::G2W,
                                    /* .pseudorange =  */ Pseudorange{ .value = 22458057.204, .SSI = 5 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 91962017.258, .SSI = 5, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { G01, 3 },
                                    /* .code =         */ Code::G1C,
                                    /* .pseudorange =  */ Pseudorange{ .value = 25435674.322, .SSI = 5 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 133665419.680, .SSI = 5, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { G01, 3 },
                                    /* .code =         */ Code::G1W,
                                    /* .pseudorange =  */ Pseudorange{ .value = 25435674.170, .SSI = 1 },
                                    /* .carrierPhase = */ std::nullopt,
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { G02, 3 },
                                    /* .code =         */ Code::G2W,
                                    /* .pseudorange =  */ Pseudorange{ .value = 25435671.028, .SSI = 1 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 104154867.885, .SSI = 1, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { G02, 3 },
                                    /* .code =         */ Code::G2L,
                                    /* .pseudorange =  */ Pseudorange{ .value = 25435671.575, .SSI = 4 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 104154891.757, .SSI = 4, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { G05, 3 },
                                    /* .code =         */ Code::G5Q,
                                    /* .pseudorange =  */ Pseudorange{ .value = 25435670.780, .SSI = 5 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 99815098.124, .SSI = 5, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { G01, 5 },
                                    /* .code =         */ Code::G1C,
                                    /* .pseudorange =  */ Pseudorange{ .value = 23631237.367, .SSI = 7 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 124183008.009, .SSI = 7, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { G01, 5 },
                                    /* .code =         */ Code::G1W,
                                    /* .pseudorange =  */ Pseudorange{ .value = 23631237.215, .SSI = 4 },
                                    /* .carrierPhase = */ std::nullopt,
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { G02, 5 },
                                    /* .code =         */ Code::G2W,
                                    /* .pseudorange =  */ Pseudorange{ .value = 23631230.734, .SSI = 4 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 96765955.343, .SSI = 4, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { G02, 5 },
                                    /* .code =         */ Code::G2L,
                                    /* .pseudorange =  */ Pseudorange{ .value = 23631231.916, .SSI = 6 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 96765963.344, .SSI = 6, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { I05, 2 },
                                    /* .code =         */ Code::I5A,
                                    /* .pseudorange =  */ Pseudorange{ .value = 38518766.840, .SSI = 6 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 151155936.366, .SSI = 6, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { J01, 2 },
                                    /* .code =         */ Code::J1C,
                                    /* .pseudorange =  */ Pseudorange{ .value = 44639648.831, .SSI = 5 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 234582941.795, .SSI = 5, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { J02, 2 },
                                    /* .code =         */ Code::J2L,
                                    /* .pseudorange =  */ Pseudorange{ .value = 44639646.392, .SSI = 4 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 182791881.933, .SSI = 4, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { J05, 2 },
                                    /* .code =         */ Code::J5Q,
                                    /* .pseudorange =  */ Pseudorange{ .value = 44639643.975, .SSI = 5 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 175175559.202, .SSI = 5, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { R01, 6 },
                                    /* .code =         */ Code::R1C,
                                    /* .pseudorange =  */ Pseudorange{ .value = 20462782.695, .SSI = 7 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 109193382.222, .SSI = 7, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { R01, 6 },
                                    /* .code =         */ Code::R1P,
                                    /* .pseudorange =  */ Pseudorange{ .value = 20462781.853, .SSI = 7 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 109193379.224, .SSI = 7, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { R01, 7 },
                                    /* .code =         */ Code::R1C,
                                    /* .pseudorange =  */ Pseudorange{ .value = 19719559.112, .SSI = 8 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 105560396.176, .SSI = 8, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { R01, 7 },
                                    /* .code =         */ Code::R1P,
                                    /* .pseudorange =  */ Pseudorange{ .value = 19719559.387, .SSI = 8 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 105560382.199, .SSI = 8, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { R02, 7 },
                                    /* .code =         */ Code::R2P,
                                    /* .pseudorange =  */ Pseudorange{ .value = 19719553.220, .SSI = 8 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 82102486.157, .SSI = 8, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { R02, 7 },
                                    /* .code =         */ Code::R2C,
                                    /* .pseudorange =  */ Pseudorange{ .value = 19719553.035, .SSI = 8 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 82102500.147, .SSI = 8, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { R01, 9 },
                                    /* .code =         */ Code::R1C,
                                    /* .pseudorange =  */ Pseudorange{ .value = 21540204.821, .SSI = 8 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 115023494.764, .SSI = 8, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { R01, 9 },
                                    /* .code =         */ Code::R1P,
                                    /* .pseudorange =  */ Pseudorange{ .value = 21540205.028, .SSI = 8 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 115023499.767, .SSI = 8, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { R02, 9 },
                                    /* .code =         */ Code::R2P,
                                    /* .pseudorange =  */ Pseudorange{ .value = 21540199.089, .SSI = 7 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 89462698.493, .SSI = 7, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { R02, 9 },
                                    /* .code =         */ Code::R2C,
                                    /* .pseudorange =  */ Pseudorange{ .value = 21540198.817, .SSI = 7 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 89462700.485, .SSI = 7, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { R03, 9 },
                                    /* .code =         */ Code::R3Q,
                                    /* .pseudorange =  */ Pseudorange{ .value = 21540183.089, .SSI = 7 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 86364723.501, .SSI = 7, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { S01, 23 },
                                    /* .code =         */ Code::S1C,
                                    /* .pseudorange =  */ Pseudorange{ .value = 38660624.330, .SSI = 7 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 203163010.934, .SSI = 7, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
          GnssObs::ObservationData{ /* .satSigId =     */ { S05, 23 },
                                    /* .code =         */ Code::S5I,
                                    /* .pseudorange =  */ Pseudorange{ .value = 38660605.426, .SSI = 6 },
                                    /* .carrierPhase = */ CarrierPhase{ .value = 151712562.074, .SSI = 6, .LLI = 0 },
                                    /* .doppler =      */ std::nullopt,
                                    /* .CN0 =          */ std::nullopt },
      } },
};
} // namespace NAV::TESTS::RinexObsFileTests::v3_04