
name: 'setup_cache'
description: 'sets up the shared cache'
inputs:
  compiler:
    required: true
    type: string
  build_type:
    required: true
    type: string
  doxygen:
    required: true
    type: string
    default: "OFF"


runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        # You might want to add .ccache to your cache configuration?
        path: |
          ${{ env.CONAN_USER_HOME }}
          ~/.cache/pip
        key: ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}-${{ inputs.doxygen }}-${{ hashFiles('./conanfile.txt')}}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}-${{ inputs.doxygen }}-${{ hashFiles('./conanfile.txt') }}
